name: Atualiza dados a cada 15min
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Instala Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instala dependências
        run: npm install
      - name: Executa script de atualização
        run: node backend/updateData.js
      - name: Commit e push dos dados
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/*.json
          git commit -m "Atualiza dados automáticos"
          git push
        continue-on-error: true
